services:
  api:
    build: ./api
    ports:
      - "3000:3000"
    env_file:
      - ./api/.env
    environment:
      NOMINATIM_URL: http://nominatim:8080
    restart: unless-stopped
    networks:
      - gat4-net

  client:
    build: ./client
    ports:
      - "3001:3001"
    env_file:
      - ./client/.env

networks:
  gat4-net:
    name: gat4-net
    external: true
