services:
  nominatim:
    image: mediagis/nominatim:5.3
    ports:
      - "3002:8080"
    environment:
      PBF_PATH: /nominatim/data/porto-alegre.osm.pbf
      NOMINATIM_PASSWORD: ${NOMINATIM_PASSWORD}
    volumes:
      - nominatim-data:/var/lib/postgresql/14/main
      - .:/nominatim/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/status"]
      interval: 2m
      timeout: 10s
      retries: 10
      start_period: 50m
    networks:
      - gat4-net

volumes:
  nominatim-data:

networks:
  gat4-net:
    name: gat4-net
